require 'net/http'
require 'date'
require 'JSON'
require 'hashie'
require 'nokogiri'

require 'gamertag/simple_profile'
require 'gamertag/played_games'
require 'gamertag/profile'
require 'gamertag/version'
